import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "nextjs-tailwind-chatbot",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // const cookieStore = await cookies();
  // const token = cookieStore.get('guestToken');
  //   if (!token) {
  //   redirect('/api/set-token?returnTo=/');
  // }
  return (
  <html lang="en">
    <body style={{'background':'#edf2f7'}}
      className={`h-screen overflow-hidden flex items-center`}
    >
      {children}
    </body>
  </html>
  );
}
